export const audioNames = [
	"theme-bright.mp3",
	"theme-calm.mp3",
	"theme-electronic.mp3",
	"theme-game.mp3",
	"theme-medieval.mp3",
	"theme-metal.mp3",
	"highDown.mp3",
	"highUp.mp3",
	"laser1.mp3",
	"laser2.mp3",
	"laser3.mp3",
	"laser4.mp3",
	"laser5.mp3",
	"laser6.mp3",
	"laser7.mp3",
	"laser8.mp3",
	"laser9.mp3",
	"lowDown.mp3",
	"lowRandom.mp3",
	"lowThreeTone.mp3",
	"pepSound1.mp3",
	"pepSound2.mp3",
	"pepSound3.mp3",
	"pepSound4.mp3",
	"pepSound5.mp3",
	"phaseJump1.mp3",
	"phaseJump2.mp3",
	"phaseJump3.mp3",
	"phaseJump4.mp3",
	"phaseJump5.mp3",
	"phaserDown1.mp3",
	"phaserDown2.mp3",
	"phaserDown3.mp3",
	"phaserUp1.mp3",
	"phaserUp2.mp3",
	"phaserUp3.mp3",
	"phaserUp4.mp3",
	"phaserUp5.mp3",
	"phaserUp6.mp3",
	"phaserUp7.mp3",
	"powerUp10.mp3",
	"powerUp11.mp3",
	"powerUp12.mp3",
	"powerUp1.mp3",
	"powerUp2.mp3",
	"powerUp3.mp3",
	"powerUp4.mp3",
	"powerUp5.mp3",
	"powerUp6.mp3",
	"powerUp7.mp3",
	"powerUp8.mp3",
	"powerUp9.mp3",
	"spaceTrash1.mp3",
	"spaceTrash2.mp3",
	"spaceTrash3.mp3",
	"spaceTrash4.mp3",
	"spaceTrash5.mp3",
	"threeTone1.mp3",
	"threeTone2.mp3",
	"tone1.mp3",
	"twoTone1.mp3",
	"twoTone2.mp3",
	"zap1.mp3",
	"zap2.mp3",
	"zapThreeToneDown.mp3",
	"zapThreeToneUp.mp3",
	"zapTwoTone2.mp3",
	"zapTwoTone.mp3",
];

export const characterNames = [
	"Character1.glb",
	"Character2.glb",
	"Character3.glb",
	"Character4.glb",
	"Person.glb",
	"Cat.glb",
	"Monkey.glb",
	"scaletest.glb",
];

export const multiObjectNames = [
	"tree.glb",
	"tree2.glb",
	"tree3.glb",
	"tree4.glb",
	"hut.glb",
	"hut2.glb",
	"hut3.glb",
	"hut4.glb",
	"rocks.glb",
	"rocks2.glb",
	"rocks3.glb",
	"rocks4.glb",
	"boat.glb",
];

export const objectNames = [
	"Star.glb",
	"Heart.glb",
	"Coin.glb",
	"egg.glb",
	"Gem1.glb",
	"Gem2.glb",
	"Gem3.glb",
];

export const objectColours = {
	"Star.glb": ["#FFD700"], // Gold
	"Heart.glb": ["#FF69B4"], // Hot Pink
	"Coin.glb": ["#F4C542"], // Light Gold
	"egg.glb": ["#fffcec"], // Yellow White
	"Gem1.glb": ["#00BFFF"], // Deep Sky Blue
	"Gem2.glb": ["#8A2BE2"], // Blue Violet
	"Gem3.glb": ["#FF4500"], // Orange Red
	"tree.glb": ["#66CDAA", "#CD853F"],
	"tree2.glb": ["#7F9F7F", "#A1623B"],
	"tree3.glb": ["#403C3C", "#312616"],
	"tree4.glb": ["#0D5B28", "#6D6C51"],
	"rocks.glb": ["#898D86", "#99a83d"],
	"rocks2.glb": ["#898D86", "#99a83d"],
	"rocks3.glb": ["#898D86", "#99a83d"],
	"rocks4.glb": ["#898D86", "#99a83d","#6BC6EF", "#f9f9f9"],
	"hut.glb": ["#B66946", "#5F2524", "#C25A5C", "#E1B46E", "#3BACBA", "#878787"],
	"hut2.glb": ["#da6d42", "#FFD700", "#FF4500", "#8A2BE2", "#2C28E7", "#878787"],
	"hut3.glb": ["#EEB975", "#6CC3C1", "#9DC45C", "#F6DAB6", "#F3B4BE", "#878787"],
	"hut4.glb": ["#F2E8CF", "#BC4749", "#EEB975", "#386641", "#6A994E", "#878787"],
	
	"boat.glb": ["#FFFCF0", "#FF89DB", "#E7223B", "#3AE744", "#878787"],
};

export const modelNames = [
	"Flock.glb",
	"Character.glb",
	//"bird.glb",
	"boat.glb",
];

export const mapNames = [
	["Circular Depression", "circular_depression.png"],
	["Checkerboard", "checkerboard.png"],
	["Sloped Plane", "sloped_plane.png"],
	["Cove Plateau", "cove_plateau.png"],
	["Random Hills", "random_hills.png"],
	["Diagonal Ridge", "diagonal_ridge.png"],
	["Mixed Heights", "mixed_heights.png"],
	["Uneven Terrain", "uneven_terrain.png"],
];

export const animationNames = [
	["Idle", "Idle"],
	["Walk", "Walk"],
	["Run", "Run"],
	["Wave", "Wave"],
	["Yes", "Yes"],
	["No", "No"],
	["Duck", "Duck"],
	["Fall", "Fall"],
	["Fly", "Fly"],
	["Jump", "Jump"],
	["Flip", "Flip"],
	["Dance1", "Dance1"],
	["Dance2", "Dance2"],
	["Dance3", "Dance3"],
	["Dance4", "Dance4"],
	["Jump Idle", "Jump_Idle"],
	["Jump Land", "Jump_Land"],
	["Punch", "Punch"],
	["Run Attack", "Run_Attack"],
	["Run Hold", "Run_Hold"],
	["Walk Hold", "Walk_Hold"],
	["Idle_Hold", "Idle_Hold"],
	["Hit React", "HitReact"],
	["Idle Attack", "Idle_Attack"],
];

export const materialNames = [
	"none.png",
	"arrows.png",
	"brick.png",
	"carpet.png",
	"circles.png",
	"eyeball.png",
	"fabric.png",
	"fishes.png",
	"flowers.png",
	"fruit.png",
	"grass.png",
	"leaves.png",
	"marble.png",
	"mushroom.png",
	"rough.png",
	"shapes.png",
	"stars.png",
	"swirl.png",
	"tiles.png",
	"triangles.png",
	"wiggles.png",
	"windmill.png",
	"wood.png",
];
