export const audioNames = [
	"theme-bright.ogg",
	"theme-calm.ogg",
	"theme-electronic.ogg",
	"theme-electronic.mp3",
	"theme-game.ogg",
	"theme-medieval.ogg",
	"theme-metal.ogg",
	"highDown.ogg",
	"highUp.ogg",
	"laser1.ogg",
	"laser2.ogg",
	"laser3.ogg",
	"laser4.ogg",
	"laser5.ogg",
	"laser6.ogg",
	"laser7.ogg",
	"laser8.ogg",
	"laser9.ogg",
	"lowDown.ogg",
	"lowRandom.ogg",
	"lowThreeTone.ogg",
	"pepSound1.ogg",
	"pepSound2.ogg",
	"pepSound3.ogg",
	"pepSound4.ogg",
	"pepSound5.ogg",
	"phaseJump1.ogg",
	"phaseJump2.ogg",
	"phaseJump3.ogg",
	"phaseJump4.ogg",
	"phaseJump5.ogg",
	"phaserDown1.ogg",
	"phaserDown2.ogg",
	"phaserDown3.ogg",
	"phaserUp1.ogg",
	"phaserUp2.ogg",
	"phaserUp3.ogg",
	"phaserUp4.ogg",
	"phaserUp5.ogg",
	"phaserUp6.ogg",
	"phaserUp7.ogg",
	"powerUp10.ogg",
	"powerUp11.ogg",
	"powerUp12.ogg",
	"powerUp1.ogg",
	"powerUp2.ogg",
	"powerUp3.ogg",
	"powerUp4.ogg",
	"powerUp5.ogg",
	"powerUp6.ogg",
	"powerUp7.ogg",
	"powerUp8.ogg",
	"powerUp9.ogg",
	"spaceTrash1.ogg",
	"spaceTrash2.ogg",
	"spaceTrash3.ogg",
	"spaceTrash4.ogg",
	"spaceTrash5.ogg",
	"threeTone1.ogg",
	"threeTone2.ogg",
	"tone1.ogg",
	"twoTone1.ogg",
	"twoTone2.ogg",
	"zap1.ogg",
	"zap2.ogg",
	"zapThreeToneDown.ogg",
	"zapThreeToneUp.ogg",
	"zapTwoTone2.ogg",
	"zapTwoTone.ogg",
];

export const characterNames = [
	"Character1.glb",
	"Character2.glb",
	"Character3.glb",
	"Character4.glb",
	"Person.glb",
	"Cat.glb",
	"Monkey.glb",
];

export const multiObjectNames = [
	"tree.glb",
	"tree2.glb",
	"tree3.glb",
	"tree4.glb",
	"hut.glb",
	"hut2.glb",
	"hut3.glb",
	"hut4.glb",
	"boat.glb",
	"rocks.glb",
	"rocks2.glb",
	"rocks3.glb",
];

export const objectNames = [
	"Star.glb",
	"Heart.glb",
	"Coin.glb",
	"Gem1.glb",
	"Gem2.glb",
	"Gem3.glb",
];

export const objectColours = {
	"Star.glb": ["#FFD700"], // Gold
	"Heart.glb": ["#FF69B4"], // Hot Pink
	"Coin.glb": ["#F4C542"], // Light Gold
	"Gem1.glb": ["#00BFFF"], // Deep Sky Blue
	"Gem2.glb": ["#8A2BE2"], // Blue Violet
	"Gem3.glb": ["#FF4500"], // Orange Red
	"tree.glb": ["#66CDAA", "#CD853F"],
	"tree2.glb": ["#4CBB17", "#A1623B"],
	"tree3.glb": ["#7F9F7F", "#D8D8D8"],
	"tree4.glb": ["#0D5B28", "#6D6C51"],
	"rocks.glb": ["#898D86", "#99a83d"],
	"rocks2.glb": ["#898D86", "#99a83d"],
	"rocks3.glb": ["#898D86", "#99a83d"],
	"hut.glb": [
		"#814C22",
		"#231E1D",
		"#FFF4EC",
		"#E7AF3A",
		"#E72243",
		"#878787",
	],
	"hut2.glb": [
		"#00BFFF",
		"#FFD700",
		"#FF4500",
		"#8A2BE2",
		"#2C28E7",
		"#878787",
	],
	"hut3.glb": ["#50C878", "#FFBF00", "#FE5A1D", "#B09B6B", "#878787"],
	"hut4.glb": ["#FFFCF0", "#FF89DB", "#E7223B", "#3AE744", "#878787"],
	"boat.glb": ["#FFFCF0", "#FF89DB", "#E7223B", "#3AE744", "#878787"],
};

export const modelNames = [
	"Flock.glb",
	"Character.glb",
	//"bird.glb",
	"boat.glb",
];

export const mapNames = [
	["Circular Depression", "circular_depression.png"],
	["Checkerboard", "checkerboard.png"],
	["Sloped Plane", "sloped_plane.png"],
	["Cove Plateau", "cove_plateau.png"],
	["Random Hills", "random_hills.png"],
	["Diagonal Ridge", "diagonal_ridge.png"],
	["Mixed Heights", "mixed_heights.png"],
	["Uneven Terrain", "uneven_terrain.png"],
];

export const animationNames = [
	["Idle", "Idle"],
	["Walk", "Walk"],
	["Run", "Run"],
	["Wave", "Wave"],
	["Yes", "Yes"],
	["No", "No"],
	["Duck", "Duck"],
	["Fall", "Fall"],
	["Fly", "Fly"],
	["Jump", "Jump"],
	["Flip", "Flip"],
	["Dance1", "Dance1"],
	["Dance2", "Dance2"],
	["Dance3", "Dance3"],
	["Dance4", "Dance4"],
	["Jump Idle", "Jump_Idle"],
	["Jump Land", "Jump_Land"],
	["Punch", "Punch"],
	["Run Attack", "Run_Attack"],
	["Run Hold", "Run_Hold"],
	["Walk Hold", "Walk_Hold"],
	["Idle_Hold", "Idle_Hold"],
	["Hit React", "HitReact"],
	["Idle Attack", "Idle_Attack"],
];

export const materialNames = [
	"none.png",
	"arrows.png",
	"brick.png",
	"carpet.png",
	"circles.png",
	"eyeball.png",
	"fabric.png",
	"fishes.png",
	"flowers.png",
	"fruit.png",
	"grass.png",
	"leaves.png",
	"mushroom.png",
	"rough.png",
	"shapes.png",
	"stars.png",
	"swirl.png",
	"tiles.png",
	"triangles.png",
	"wiggles.png",
	"windmill.png",
	"wood.png",
];
