import { getDropdownOption } from "./main/translation.js";

export const audioNames = [
	"theme-bright.mp3",
	"theme-calm.mp3",
	"theme-electronic.mp3",
	"theme-game.mp3",
	"theme-medieval.mp3",
	"theme-metal.mp3",
	"highDown.mp3",
	"highUp.mp3",
	"laser1.mp3",
	"laser2.mp3",
	"laser3.mp3",
	"laser4.mp3",
	"laser5.mp3",
	"laser6.mp3",
	"laser7.mp3",
	"laser8.mp3",
	"laser9.mp3",
	"lowDown.mp3",
	"lowRandom.mp3",
	"lowThreeTone.mp3",
	"pepSound1.mp3",
	"pepSound2.mp3",
	"pepSound3.mp3",
	"pepSound4.mp3",
	"pepSound5.mp3",
	"phaseJump1.mp3",
	"phaseJump2.mp3",
	"phaseJump3.mp3",
	"phaseJump4.mp3",
	"phaseJump5.mp3",
	"phaserDown1.mp3",
	"phaserDown2.mp3",
	"phaserDown3.mp3",
	"phaserUp1.mp3",
	"phaserUp2.mp3",
	"phaserUp3.mp3",
	"phaserUp4.mp3",
	"phaserUp5.mp3",
	"phaserUp6.mp3",
	"phaserUp7.mp3",
	"powerUp10.mp3",
	"powerUp11.mp3",
	"powerUp12.mp3",
	"powerUp1.mp3",
	"powerUp2.mp3",
	"powerUp3.mp3",
	"powerUp4.mp3",
	"powerUp5.mp3",
	"powerUp6.mp3",
	"powerUp7.mp3",
	"powerUp8.mp3",
	"powerUp9.mp3",
	"spaceTrash1.mp3",
	"spaceTrash2.mp3",
	"spaceTrash3.mp3",
	"spaceTrash4.mp3",
	"spaceTrash5.mp3",
	"threeTone1.mp3",
	"threeTone2.mp3",
	"tone1.mp3",
	"twoTone1.mp3",
	"twoTone2.mp3",
	"zap1.mp3",
	"zap2.mp3",
	"zapThreeToneDown.mp3",
	"zapThreeToneUp.mp3",
	"zapTwoTone2.mp3",
	"zapTwoTone.mp3",
];

export const characterNames = [
	"Liz1.glb",
	"Liz2.glb",
	"Liz3.glb",
	"Liz4.glb",
	"Liz5.glb",
	"Liz6.glb",
	"Block1.glb",
	"Block2.glb",
	"Block3.glb",
	"Block4.glb",
	"Block5.glb",
	"Block6.glb",
	"Character1.glb",
	"Character2.glb",
	"Character3.glb",
	"Character4.glb",
];

export const multiObjectNames = [
	"tree.glb",
	"tree2.glb",
	"tree3.glb",
	"tree4.glb",
	"hut.glb",
	"hut2.glb",
	"hut3.glb",
	"hut4.glb",
	"rocks.glb",
	"rocks2.glb",
	"rocks3.glb",
	"rocks4.glb",
	"pond.glb",
	"boat.glb",
	"airplane.glb",
	"airplane2.glb",
	"skateboard.glb",
	"humped.glb",
	"jetty.glb",
	"flower.glb",
	"flower2.glb",
	//"stones_straight.glb",
	//"stones_curve.glb",
];

export const objectNames = [
	"Star.glb",
	"Heart.glb",
	"Coin.glb",
	"egg.glb",
	"Gem1.glb",
	"Gem2.glb",
	"Gem3.glb",
	"Key.glb",
	"Wand.glb",
	"Hat.glb",
	"donut.glb",
	"pumpkin.glb",
	"apple.glb",
	"starboppers.glb",
	"headphones.glb",
];

export const objectColours = {
	"Star.glb": ["#FFD700", "#FFD700", "#FFD700"],
	"Heart.glb": ["#FF69B4", "#FF69B4", "#FF69B4"],
	"Coin.glb": ["#A47E1B", "#C9A227", "#76520E"],
	"egg.glb": ["#fffcec", "#fffcec", "#fffcec"],
	"Gem1.glb": ["#00BFFF", "#00BFFF", "#00BFFF"],
	"Gem2.glb": ["#8A2BE2", "#8A2BE2", "#8A2BE2"],
	"Gem3.glb": ["#FF4500", "#FF4500", "#FF4500"],
	"Key.glb": ["#A47E1B", "#C9A227", "#76520E"],
	"Wand.glb": ["#FF4500", "#8A2BE2", "#92614A"],
	"Hat.glb": ["#9D3F72", "#B5FDFD", "#3D0073"],
	"donut.glb": ["#f9cb9c", "#fba0c3"],
	"pumpkin.glb": ["#E78632", "#75430F"],
	"apple.glb": ["#3FAF45", "#A9323F", "#624A20"],
	"starboppers.glb": ["#FFD700", "#FFD700", "#FFD700", "#f9f9f9"],
	"headphones.glb": ["#53E0E7", "#3291E7", "#7D7D7D"],

	"tree.glb": ["#66CDAA", "#CD853F"],
	"tree2.glb": ["#7F9F7F", "#A1623B"],
	"tree3.glb": ["#403C3C", "#312616"],
	"tree4.glb": ["#0D5B28", "#6D6C51"],

	"rocks.glb": ["#898D86", "#99a83d"],
	"rocks2.glb": ["#898D86", "#99a83d"],
	"rocks3.glb": ["#898D86", "#99a83d"],
	"rocks4.glb": ["#898D86", "#99a83d", "#6BC6EF", "#f9f9f9"],
	"pond.glb": ["#00E704", "#5A91E7", "#9A9A9A"],

	"hut.glb": [
		"#B66946",
		"#5F2524",
		"#C25A5C",
		"#E1B46E",
		"#3BACBA",
		"#878787",
	],
	"hut2.glb": [
		"#814C22",
		"#231E1D",
		"#FFF6A6",
		"#E7AF3A",
		"#E73627",
		"#878787",
	],
	"hut3.glb": [
		"#F6DAB6",
		"#6CC3C1",
		"#9DC45C",
		"#EEB975",
		"#F3B4BE",
		"#878787",
	],
	"hut4.glb": [
		"#F2E8CF",
		"#BC4749",
		"#EEB975",
		"#AF1B3F",
		"#6A994E",
		"#878787",
	],

	"boat.glb": [
		"#4F8A46",
		"#E7D48E",
		"#E76635",
		"#E76C69",
		"#5E64E7",
		"#4A4A4A",
		"#AAAAAA",
		"#E711CD",
	],

	"airplane.glb": ["#E75D43", "#6A6A6A", "#E7C777"],

	"airplane2.glb": ["#6A6A6A", "#E75D43", "#E7C777"],

	"skateboard.glb": ["#E769D3", "#484848", "#251BE7"],

	"rhino.glb": ["#6D6B6C", "#F6F6F6", "#373737", "#230F0F"],

	"humped.glb": ["#FFA869", "#7E5024", "#E76F31"],
	"jetty.glb": ["#FFA869", "#7E5024", "#E76F31"],
	"flower.glb": ["#E73F9F", "#4AB700", "#E7D535"],
	"flower2.glb": ["#E73F9F", "#E7774E", "#E7D535"],
	//"stones_straight.glb": ["#E73F9F", "#4AB700", "#E7D535","#dce0d9", "#fbf6ef", "#ead7c3"],
	//"stones_curve.glb": ["#E73F9F", "#4AB700", "#E7D535","#dce0d9", "#fbf6ef", "#ead7c3"],
};

export const modelNames = [
	"Flock.glb",
	//"Character.glb",
	//"bird.glb",
	//"boat.glb",
	"rhino.glb",
	//"Seagull.glb",
];

export const blockNames = [
	"Character1.glb",
	"Character2.glb",
	"Character3.glb",
	"Character4.glb",
	"Flock.glb",
	"Character.glb",
	"rhino.glb",
	//"Seagull.glb",
];

export const modelAnimationNames = [
	"Flock.glb",
	"rhino.glb",
	//"Seagull.glb",
];

export function mapNames() {
	return [
		getDropdownOption("circular_depression.png"),
		getDropdownOption("checkerboard.png"),
		getDropdownOption("sloped_plane.png"),
		getDropdownOption("cove_plateau.png"),
		getDropdownOption("random_hills.png"),
		getDropdownOption("diagonal_ridge.png"),
		getDropdownOption("mixed_heights.png"),
		getDropdownOption("uneven_terrain.png"),
	];
}

export function animationNames() {
	return [
		getDropdownOption("Idle"),
		getDropdownOption("Walk"),
		getDropdownOption("Run"),
		getDropdownOption("Wave"),
		getDropdownOption("Yes"),
		getDropdownOption("No"),
		getDropdownOption("Duck"),
		getDropdownOption("Fall"),
		getDropdownOption("Fly"),
		getDropdownOption("Jump"),
		getDropdownOption("Flip"),
		getDropdownOption("Dance1"),
		getDropdownOption("Dance2"),
		getDropdownOption("Dance3"),
		getDropdownOption("Dance4"),
		getDropdownOption("Punch"),
		getDropdownOption("HitReact"),
		getDropdownOption("Idle_Hold"),
		getDropdownOption("Walk_Hold"),
		getDropdownOption("Run_Hold"),
		getDropdownOption("Idle_Attack"),
		getDropdownOption("Walk_Attack"),
		getDropdownOption("Run_Attack"),
		getDropdownOption("Sit_Down"),
		getDropdownOption("Sitting"),
		getDropdownOption("Stand_Up"),
		getDropdownOption("Wobble"),
		getDropdownOption("Clap"),
		getDropdownOption("Jump_Idle"),
		getDropdownOption("Jump_Land"),
	];
}

export const materialNames = [
	"none.png",
	"arrows.png",
	"bricks.png",
	"carbonfibre.png",
	"carpet.png",
	"circles.png",
	"eyeball.png",
	"fabric.png",
	"fishes.png",
	"flowers.png",
	"fruit.png",
	"grass.png",
	"gravel.png",
	"leaves.png",
	"marble.png",
	"mushroom.png",
	"planks.png",
	"rough.png",
	"shapes.png",
	"stars.png",
	"stripes.png",
	"swirl.png",
	"tiles.png",
	"triangles.png",
	"wiggles.png",
	"windmill.png",
	"wood.png",
];

export const attachNames = ["Hold", "Head"];

export const attachBlockMapping = {
	Hold: "Hold",
	Head: "Head",
};

export const attachMixamoMapping = {
	Hold: "mixamorig:LeftHand",
	Head: "mixamorig:Head",
};

export function getAttachNames() {
	return attachNames.map((name) => getDropdownOption(name));
}
